### ISSUE TITLE
Using aws-role-to-assume causes start to fail

### ISSUE THREAD

**Issue by andycockerill-cpi** [superblk/ec2-actions-runner#10]
Hi,

When I use aws-role-to-assume I get:

"Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers"

This appears to be related to https://github.com/aws-actions/configure-aws-credentials/issues/271 which has apparently been fixed in v1.6.0. Is it possible for you to update "start" to point to the fixed version?

**Comment by andycockerill-cpi** [comment]
To see for myself, I've forked this repo and updated it myself and I'm getting the same error, so this may not be the issue.

**Comment by jpalomaki** [comment]
@andycockerill-cpi Are you attempting to use [OIDC](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) in the workflow, or simple role assumption using IAM user access keys?

**Comment by jpalomaki** [comment]
I quickly tested role assume with static access keys (IAM user who can assume the role) using this kind of config (some details omitted for brevity and redacted):
```
- id: runner
  name: Start runner
  uses: superblk/ec2-actions-runner/start@v0.8.1
  with:
    aws-region: <aws region>
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-role-to-assume: arn:aws:iam::<account ID>:role/<path/to/role>
    ...
```
This worked okay.

I will next test OIDC-based role assume, as that would allow us to skip the static AWS access keys alltogether (so its safer and less verbose).
